apiDir: "../keycloak-oidc-rest-api/src/main/java"
apiPackagePath: "com.acme.keycloak.oidc.rest"
application:
    baseURI: "/keycloak-oidc"
    className: "KeycloakOidcApplication"
    name: "Com.Acme.Keycloak.Oidc"
author: "hungtvb"
javaEEPackage: "jakarta"
